"use client";

import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Copy, Loader2, ShieldCheck, ShieldOff, Smartphone } from "lucide-react";
import { toast } from "sonner";
import { mfaApi } from "@/lib/api/mfa";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

/**
 * Authenticator-app (TOTP) two-factor authentication. Once a factor is
 * verified, the database itself refuses this account's data to sessions
 * that have not passed the second step.
 */
export default function MfaSettings() {
  const queryClient = useQueryClient();
  const [enrollment, setEnrollment] = useState(null); // { factorId, qrCode, secret }
  const [code, setCode] = useState("");

  const { data: factors = [], isLoading } = useQuery({
    queryKey: ["mfa-factors"],
    queryFn: () => mfaApi.listFactors(),
  });
  const verified = factors.filter((factor) => factor.status === "verified");

  const refresh = () => queryClient.invalidateQueries({ queryKey: ["mfa-factors"] });

  const start = useMutation({
    mutationFn: () => mfaApi.enrollTotp(`Authenticator ${new Date().toISOString().slice(0, 10)}`),
    onSuccess: (data) => {
      setEnrollment(data);
      setCode("");
    },
    onError: (err) => toast.error(err.message),
  });

  const confirm = useMutation({
    mutationFn: () => mfaApi.verify(enrollment.factorId, code),
    onSuccess: () => {
      setEnrollment(null);
      setCode("");
      refresh();
      toast.success("Two-factor authentication is on");
    },
    onError: (err) => {
      setCode("");
      toast.error(err.message);
    },
  });

  const remove = useMutation({
    mutationFn: (factorId) => mfaApi.unenroll(factorId),
    onSuccess: () => {
      refresh();
      toast.success("Authenticator removed");
    },
    onError: (err) => toast.error(err.message),
  });

  return (
    <section className="space-y-4" aria-labelledby="mfa-heading">
      <div className="flex items-center gap-2">
        <ShieldCheck className="h-4 w-4 text-muted-foreground" />
        <h3 id="mfa-heading" className="text-sm font-semibold text-foreground">
          Two-factor authentication
        </h3>
      </div>

      {isLoading ? (
        <div className="flex items-center gap-2 text-sm text-muted-foreground" role="status">
          <Loader2 className="h-4 w-4 animate-spin" /> Checking…
        </div>
      ) : verified.length > 0 ? (
        <ul className="space-y-2">
          {verified.map((factor) => (
            <li
              key={factor.id}
              className="flex items-center justify-between gap-3 rounded-xl border border-success/30 bg-success/5 px-4 py-3"
            >
              <div className="flex min-w-0 items-center gap-3">
                <Smartphone className="h-5 w-5 shrink-0 text-success" />
                <div className="min-w-0">
                  <p className="truncate text-sm font-medium text-foreground">
                    {factor.friendly_name || "Authenticator app"}
                  </p>
                  <p className="text-xs text-muted-foreground">
                    Active since {new Date(factor.created_at).toLocaleDateString()}
                  </p>
                </div>
              </div>
              <Button
                variant="outline"
                size="sm"
                disabled={remove.isPending}
                onClick={() => {
                  if (window.confirm("Turn off two-factor authentication for this account?")) {
                    remove.mutate(factor.id);
                  }
                }}
                className="shrink-0 rounded-lg text-destructive hover:bg-destructive/10 hover:text-destructive"
              >
                <ShieldOff className="mr-1.5 h-4 w-4" /> Remove
              </Button>
            </li>
          ))}
        </ul>
      ) : enrollment ? (
        <div className="space-y-4 rounded-xl border border-border bg-muted/40 p-4">
          <ol className="list-decimal space-y-1 pl-5 text-sm text-muted-foreground">
            <li>Scan the QR code with an authenticator app (Google Authenticator, 1Password, Authy…).</li>
            <li>Enter the 6-digit code it shows to finish.</li>
          </ol>
          <div className="flex flex-col items-center gap-4 sm:flex-row sm:items-start">
            {/* The QR code is an SVG data URI generated by Supabase. */}
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src={enrollment.qrCode}
              alt="QR code for your authenticator app"
              width={168}
              height={168}
              className="rounded-lg bg-white p-2"
            />
            <div className="w-full space-y-3">
              <div>
                <p className="mb-1 text-xs text-muted-foreground">Can&apos;t scan? Enter this key instead:</p>
                <div className="flex items-center gap-2">
                  <code className="min-w-0 flex-1 truncate rounded-md border border-border bg-card px-2 py-1 font-mono text-xs text-foreground">
                    {enrollment.secret}
                  </code>
                  <Button
                    type="button"
                    variant="ghost"
                    size="icon"
                    aria-label="Copy setup key"
                    onClick={() => {
                      navigator.clipboard.writeText(enrollment.secret);
                      toast.success("Setup key copied");
                    }}
                  >
                    <Copy className="h-4 w-4" />
                  </Button>
                </div>
              </div>
              <form
                onSubmit={(event) => {
                  event.preventDefault();
                  confirm.mutate();
                }}
                className="flex gap-2"
              >
                <Input
                  inputMode="numeric"
                  autoComplete="one-time-code"
                  aria-label="6-digit code"
                  placeholder="123456"
                  maxLength={6}
                  value={code}
                  onChange={(e) => setCode(e.target.value.replace(/\D/g, "").slice(0, 6))}
                  className="h-10 rounded-lg bg-card text-center font-semibold tracking-[0.3em]"
                />
                <Button type="submit" disabled={code.length !== 6 || confirm.isPending} className="h-10 rounded-lg">
                  {confirm.isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : "Verify"}
                </Button>
              </form>
              <button
                type="button"
                onClick={() => setEnrollment(null)}
                className="text-xs text-muted-foreground hover:text-foreground"
              >
                Cancel
              </button>
            </div>
          </div>
        </div>
      ) : (
        <div className="flex flex-col gap-3 rounded-xl border border-border bg-card px-4 py-4 sm:flex-row sm:items-center sm:justify-between">
          <p className="text-sm text-muted-foreground">
            Require a code from your phone when signing in, so a stolen password alone is not enough.
          </p>
          <Button onClick={() => start.mutate()} disabled={start.isPending} className="shrink-0 rounded-lg">
            {start.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <ShieldCheck className="mr-2 h-4 w-4" />}
            Enable
          </Button>
        </div>
      )}
    </section>
  );
}
